### ISSUE TITLE
Missing retroarch parameters

### ISSUE THREAD

**Issue by zanac** [sebastian404/aus_japb_retroarch#2]
Need also a script.sh to help parameters needed for compile frontend of retroarch... something like:

./configure --enable-gles --enable-mali_fbdev --disable-x11 --disable-sdl2 --enable-floathard --disable-ffmpeg --disable-netplay --enable-udev --disable-sdl --disable-pulse --disable-oss --disable-freetype --disable-7zip --disable-libxml2 [and cross compile options of course!!!!]

**Comment by sebastian404** [comment]
to be added in next release
