### ISSUE TITLE
Missing kernel ref and parameters

### ISSUE THREAD

**Issue by zanac** [sebastian404/aus_japb_retroarch#3]
1- Missing which kernel is compatible with patches,
2- Where to download
3- Which parameters used to compile
4- The .config used for compile

Regard (1) and (2), i think that you used from https://codeload.github.com/linux-sunxi/linux-sunxi/zip/sunxi-3.4 version 3.4.104

(3) For compile please confirm that you use
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage modules
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=/tmp/path/to/build modules_install

For (4) add in git .configure used

**Comment by sebastian404** [comment]
Kernel patches are publish in /patches
